config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  resources :products
  #get "/product/not_found", to: "products#product_not_found"
  get "/search", to: "products#search"
  resources :product_categories
  resources :users, only: [:index]
  post "login", to: "users#log_in"
  post "logout", to: "users#log_out"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  validates :p_name, presence: { message: "Product name is empty" },
                     length: { minimum: 5, message: "Product name min 5 chars" }
  validates :p_description, presence: { message: "Product description is empty" },
                            length: { minimum: 20, message: "Min description 20 chars" }
  validates :p_price, presence: { message: "Product price is empty" },
                      numericality: { greater_than_or_equal_to: 0, message: "Price must be greater than or equal to 0" },
                      numericality: { less_than_or_equal_to: 999999.9, message: "Very high price" }
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
  before_validation :name_remove_spaces
  validates :name, presence: { message: "Category name is empty" },
                   length: { minimum: 5, message: "Category name min 5 chars" },
                   uniqueness: { message: "Category with same name already exist" }
  

  def name_remove_spaces
    self.name = name.lstrip.rstrip
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = ProductCategory.all
  end

  def new
    @category = ProductCategory.new
  end

  def create
    @category = ProductCategory.new(get_product_categories_params)
    if @category.save
      redirect_to product_category_path @category
      flash[:green] = "Category successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(get_product_categories_params)
      redirect_to product_category_path
      flash[:green] = "Category successfully updated"
    else
      redirect_to edit_product_category_path
    end
  end

  def destroy
    if @category.destroy
      redirect_to products_category_path, status: :see_other
      flash[:red] = "Category successfully deleted"
    else
    end
  end

  private

  def get_product_categories_params
    params.require(:product_category).permit(:name)
  end

  def set_category
    @category = ProductCategory.find(params.require(:id))
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(get_product_params)
    if @product.save
      redirect_to product_path @product
      flash[:green] = "Product successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(get_product_params)
      redirect_to product_path
      flash[:green] = "Product successfully updated"
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path, status: :see_other
      flash[:red] = "Product successfully deleted"
    else
    end
  end

  #def product_not_found
  #end

  def search
  end

  private

  def not_found
    redirect_to products_path
    flash[:red] = "Incorect product id"
  end

  def get_product_params
    params.require(:product).permit(:p_name, :p_description, :p_price, :product_category_id)
  end

  def set_product
    @product = Product.find(params.require(:id))
    @category = ProductCategory.find(@product.product_category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if session[:login]
      log_out
    else
    end
  end

  def log_in
    if user = User.find_by(email: params["email"])
      if user.authenticate(params["password"])
        redirect_to root_path
        session[:login] = true
        flash[:green] = "Login"
      else
        redirect_to users_path
        session[:login] = false
        flash[:red] = "Wrong password"
      end
    else
      redirect_to users_path
      session[:login] = false
      flash[:red] = "Wrong email"
    end
  end

  def log_out
    redirect_to root_path
    session[:login] = false
    flash[:red] = "Logout"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_title_helper(title_name = "")
    if title_name.present?
      content_for :title, "#{title_name} | ShopApp"
    else
      content_for :title, "ShopApp"
    end
  end

  def set_header_helper
    @categories = ProductCategory.all
    content_for :header do
      render partial: "header/header"
    end
  end

  def set_user_helper
    login = session[:login]
    login ? "Logout" : "Login"
  end

  def set_login_button_color_helper
    login = session[:login]
    login ? "btn btn-danger" : "btn"
  end

  def errors_form_helper(obj, column)
    render partial: "layouts/errors", locals: {obj: obj, column: column } if obj.errors.where(column).any?
  end

  def header_flash_helper(flash)
    alert_style = { "green" => "alert alert-success", "red" => "alert alert-danger" }
    render partial: "header/header_flash",
           locals: { alert_style: alert_style[flash.keys.first], alert_text: flash[flash.keys.first] }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/header/_header.html.erb
<!-- Navbar start -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow sticky-top">
  <div class="container-fluid">
    <%= link_to 'ShopApp', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <div class="dropdown">
            <a class="btn dropdown-toggle" href="<%=products_path%>" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              Products
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><a class="dropdown-item" href="<%=products_path%>">All products</a></li>
              <li><a class="dropdown-item" href="<%=new_product_path%>">Add new product</a></li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <div class="dropdown">
            <a class="btn dropdown" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
              Categories
            </a>
          </div>
        </li>
        <div class="dropdown">
          <a class="<%=set_login_button_color_helper%>" href="<%=users_path%>" role="button" >
            <%=set_user_helper%>
          </a>
        </div>
      </ul>
      <%= form_with url: search_path,class:'d-flex', method: :get do |form| %>
        <%= form.text_field :search, class:'form-control me-2' %>
        <%= form.submit "Search", class:'btn btn-outline-success' %>
      <% end %>
    </div>
  </div>
</nav>
<!-- Navbar end -->
<div class="container-fluid">
  <!-- Flashing start -->
  <% if flash.any? %>
    <%=header_flash_helper(flash)%>
  <% end %>
  <!-- Flashing end -->
  <!-- Sidebar for categories start -->
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasExampleLabel">Categories</h5>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div>
        <%=link_to 'Add category', new_product_category_path, class: ' btn btn-outline-secondary'%>
        <ul class="list-group">
          <%@categories.each do |cat|%>
            <li class="list-group-item btn-outline-secondary">
              <%=link_to "#{cat.name} | ( #{cat.products.count} )",
                                     product_category_path(cat), class:'btn stretched-link' %></li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
  <!-- Sidebar for categories end -->

app/views/header/_header_flash.html.erb
<div class="<%=alert_style%>" role="alert"><%=alert_text%></div>

app/views/layouts/_errors.html.erb
<div class="alert-danger rounded-bottom p-1">
  <%obj.errors.where(column).each do |error|%>
    <div>
      <%=error.message%>
    </div>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% set_title_helper if !content_for?(:title)%>
    <title><%=yield :title%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   </head>
  <body>
    <%set_header_helper%>
    <%=yield :header%>
    <div class="d-flex justify-content-center">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/index.html.erb
<%set_title_helper('Index page')%>
Index page

app/views/product_categories/_product_category_form.html.erb
<div class="p-3 mt-5 shadow col-md-12 col-lg-10 col-xl-8">
  <%=form_with model: @category do |c|%>
    <div class="mb-3 ">
      <%=c.label :category, "Category name", class: 'form-label h5'%>
      <%=c.text_field :name, class: 'form-control' %>
      <%=errors_form_helper(@category,:name)%>
    </div>
    <div class="mb-3">
      <%=c.submit "Save",class: 'btn btn-primary col-12'%>
    </div>
  <%end%>
</div>

app/views/product_categories/edit.html.erb
<%set_title_helper("Edit category #{@category.name}")%>
<%= render 'product_category_form' %>

app/views/product_categories/index.html.erb
<%set_title_helper("All categories")%>
<div class="row g-3 mt-3 m-4">
  <%@categories.each do |cat|%>
    <div class="card col-md-6 col-lg-4 col-xl-3 p-1" style="min-width:300px">
      <%=cat.products.count%> products in 
      <%=cat.name%><%=link_to "",product_category_path(cat.id), class: 'stretched-link'%>
    </div>
  <%end%>
</div>

app/views/product_categories/new.html.erb
<%set_title_helper("Add new category")%>
<%= render 'product_category_form' %>

app/views/product_categories/show.html.erb
<%set_title_helper("#{@category.name}")%>
<div class="row g-3 mt-3 m-4">
  <%@category.products.each do |p| %>
    <div class="card col-md-6 col-lg-4 col-xl-3 p-1" style="min-width:300px">
      <div class="card img bg-light", style="height:300px">
      </div>
      <div class="card-body">
        <div class="card-title text-truncate h4">
          <%=link_to "#{p.p_name}", product_path(p.id), 
                      class:'text-decoration-none text-uppercase stretched-link'%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/_errors.html.erb
<div class="alert-danger rounded-bottom p-1">
  <%@product.errors.where(column).each do |error|%>
    <div>
      <%=error.message%>
    </div>
  <%end%>
</div>

app/views/products/_product_form.html.erb
<div class="p-3 mt-5 shadow col-md-12 col-lg-10 col-xl-8">
  <%=form_with model: @product do |p|%>
    <div class="mb-3 ">
      <%=p.label :product, "Product name",class: 'form-label h5'%>
      <%=p.text_field :p_name, class: 'form-control' %>
      <%=errors_form_helper(@product,:p_name)%>
    </div>
    <div class="mb-3">
      <%=p.label :product, "Product description",class: 'form-label h5'%>
      <%=p.text_area :p_description, size: "80x5", class: 'form-control' %>
      <%=errors_form_helper(@product,:p_description)%>
    </div>
    <div class="mb-3">
      <%=p.label :product, "Product category",class: 'form-label h5'%>
      <%=p.collection_select :product_category_id, ProductCategory.all, :id, :name %>
    </div>
    <div>
    </div>
    <div class="mb-3">
      <%=p.label :product, "Product price", class: 'form-label h5'%>
      <%=p.number_field :p_price, step: :any, class: 'form-control' %>
      <%=errors_form_helper(@product,:p_price)%>
    </div>
    <div class="mb-3">
      <%=p.submit "Save",class: 'btn btn-primary col-12'%>
    </div>
  <%end%>
</div>

app/views/products/edit.html.erb
<%= render 'product_form' %>
<%set_title_helper("Edit : #{@product.p_name}")%>

app/views/products/index.html.erb
<%set_title_helper("All products")%>
<div class="row g-3 mt-3 m-4">
  <%@products.each do |p| %>
    <div class="card col-md-6 col-lg-4 col-xl-3 p-1" style="min-width:300px">
      <div class="card img bg-light", style="height:300px">
      </div>
      <div class="card-body">
        <div class="card-title text-truncate h4">
          <%=link_to "#{p.p_name}", product_path(p.id), 
                      class:'text-decoration-none text-uppercase stretched-link'%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%= render 'product_form' %>
<%set_title_helper("Add new product")%>

app/views/products/product_not_found.html.erb
<%set_title_helper("Product not found")%>
<h2>Product not found</h2>

app/views/products/search.html.erb
<%set_title_helper("Search page")%>
<h1>Search page</h1>

app/views/products/show.html.erb
<%set_title_helper("#{@product.p_name}")%>
<div class="card col-12 col-md-12 col-lg-10 col-xl-8 p-1 shadow mt-3">
  <div class="card img bg-light" style="height:500px">
  </div>
  <div class="card-body">
    <div class="card-title h3 text-center">
      <div class="h6 text-start">
        ID :  <%=@product.id%>
      </div>
      <%=@product.p_name%>
    </div>
    <div class="text-center h5">
      <%=@product.p_description%>
    </div>
    <div class="text-end">
      $ <%="%.2f" % @product.p_price%>
    </div>
    <div class="text-end">
      Cat : <%=@category.name%>
    </div>
  </div>
  <%=link_to "Edit product", edit_product_path(@product) , class:"btn btn-primary mt-2"%>
  <%= link_to 'Delete product', product_path(@product) ,
              data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'},class:"btn btn-danger mt-2" %>
</div>

app/views/users/_form_user.html.erb
<div class="p-3 mt-5 shadow col-md-12 col-lg-10 col-xl-8">
  <%=form_with url: login_path, method: :post do |user|%>
    <div class="mb-3 ">
      <%=user.label :product, "Email", class: 'form-label h5'%>
      <%=user.email_field :email, required: true, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%=user.label :password, "Password",class: 'form-label h5'%>
      <%=user.password_field :password, required: true, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%=user.submit "Log in", class: 'btn btn-primary col-12'%>
    </div>
  <%end%>
</div>

app/views/users/index.html.erb
<%= render partial: 'form_user'%>